spring.application.name=ecom-application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.h2.console.path=/h2-console
#helps us in logging all the calls going to db
spring.jpa.show-sql=true
#controlls the behavior of db when we restart the application
# create = deletes all existing tables and creates them again
#update = keeps the existing one and adds the new data
spring.jpa.hibernate.ddl-auto=create
#timeStamp2:28:40