package com.app.ecom.service;


import com.app.ecom.model.User;
import com.app.ecom.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestBody;

import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository userRepository;
//    private List<User> userList = new ArrayList<>();
//    private Long nextId = 1L; autogenerated

//    public UserService(UserRepository userRepository) {
//        this.userRepository = userRepository;
//    } RequiredArgsConstructor

    public List<User> fetchAllUsers() {
        return userRepository.findAll();
    }
    public void addUser(@RequestBody User user) {
//        user.setId(nextId++);
//        userList.add(user);
        userRepository.save(user);
    }

//    public User fetchUser(Long id) {
//        for(User user:userList){
//            if(user.getId().equals(id))return user;
//        }
//        return null;
//    }
    public Optional<User> fetchUser(Long id){
//        return userList.stream()
//                .filter(user -> user.getId().equals(id))
//                .findFirst();
        return userRepository.findById(id);
    }

    public boolean updateUser(Long id,User updatedUser){
//        return userList.stream()
//                .filter(user->user.getId().equals(id))
//                .findFirst()
//                .map(existingUser->{
//                    existingUser.setFirstName(updatedUser.getFirstName());
//                    existingUser.setLastName(updatedUser.getLastName());
//                    return true;
//                }).orElse(false);

        return userRepository.findById(id)
                .map(existingUser-> {
//                    existingUser.setFirstName(updatedUser.getFirstName());
//                    existingUser.setLastName(updatedUser.getLastName());
                    userRepository.save(existingUser);
                    return true;
                }).orElse(false);
    }
}
